name: GitHub Actions Demo
on: [push]
env: 
  SHORTSHA: $(git rev-parse --short=6 ${{ github.sha }})

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* *.github* *LICENSE*'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: ${{ env.SHORTSHA }}
        token: ${{ secrets.GITHUB_TOKEN }}
