name: GitHub Actions Demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* *.github* *LICENSE*'
    - name: tag version
      id: tag-version
      uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        tag: $tag
    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        tag: ${{ env.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
