name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* *.github* *LICENSE*'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        bodyFile: "body.md"
        tag: ${{ GITHUB_SHA }}
        token: ${{ secrets.GITHUB_TOKEN }}
